export const Getcontest = () => [
  {
    id: 100,
    name: " مهارت‌سنجی Career Days",
    date: "۱۰ مرداد ۱۳۹۹ ساعت ۱۱:۰۵",
    time: "دقیقه۸ساعت",
    numberofquestions: 7,
    participants: 2424,
    questions: [
      "نوشابه خنک",
      "افراز توان دار",
      "گراف سفید و سیاه",
      "تربچین",
      "استخدام در ترب",
      "زمین ترب",
      "در جستجوی ترب ",
    ],
  },
  {
    id: 101,
    name: "مهارت‌سنجی Career Days - آزمایشی",
    date: "۷ مرداد ۱۳۹۹ ساعت ۱۹:۰۵",
    time: "دقیقه5ساعت",
    numberofquestions: 5,
    participants: 2421,
    questions: [
      "بازی یک، سه، پنچ",
      "چاپگر",
      "خط شکسته",
      "نعلم کو؟!",
      "جاستیفای",
      "مسابقه پیچیده",
      "داده‌داری",
    ],
  },
  {
    id: 102,
    name: "مهارت‌سنشی",
    date: "۷ مرداد ",
    time: "ده5ساعت",
    numberofquestions: 5,
    participants: 2421,
    questions: ["کلید چراغ", "سلام سلام خداحافظ", "فرش دست‌باف", "آدرس‌یابی"],
  },
];
