export const Getcontest = () => [
  {
    id: 100,
    name: " مهارت‌سنجی Career Days",
    date: "۱۰ مرداد ۱۳۹۹ ساعت ۱۱:۰۵",
    time: "دقیقه۸ساعت",
    numberofquestions: 7,
    participants: 2424,
    questions: [
      { name: "نوشابه خنک", id: 62460, tag: "a", number: 1 },
      { name: "افراز توان دار", id: 62459, tag: "a", number: 10 },
      { name: "گراف سفید و سیاه", id: 62458, tag: "a", number: 12 },
      { name: "تربچین", id: 62457, tag: "a", number: 52 },
      { name: "استخدام در ترب", id: 62456, tag: "a", number: 86 },
      { name: "زمین ترب", id: 62455, tag: "a", number: 129 },
    ],
  },
  {
    id: 101,
    name: "مهارت‌سنجی Career Days - آزمایشی",
    date: "۷ مرداد ۱۳۹۹ ساعت ۱۹:۰۵",
    time: "دقیقه5ساعت",
    numberofquestions: 5,
    participants: 2421,
    questions: [
      { name: "در جستجوی ترب ", id: 62454, tag: "a", number: 495 },
      { name: "بازی یک، سه، پنچ", id: 62453, tag: "a", number: 0 },
      { name: "چاپگر", id: 62452, tag: "a", number: 6 },
      { name: "خط شکسته", id: 62451, tag: "a", number: 16 },
      { name: "نعلم کو؟!", id: 62450, tag: "a", number: 93 },
      { name: "جاستیفای", id: 62449, tag: "a", number: 57 },
      { name: "مسابقه پیچیده", id: 62448, tag: "a", number: 517 },
      { name: "داده‌داری", id: 62447, tag: "a", number: 68 },
    ],
  },
  {
    id: 102,
    name: "چالش DiffCode",
    date: "۷ مرداد ",
    time: "ده5ساعت",
    numberofquestions: 5,
    participants: 2421,
    questions: [
      { name: "کلید چراغ", id: 62446, tag: "a", number: 70 },
      { name: "سلام سلام خداحافظ", id: 62445, tag: "a", number: 68 },
      { name: "فرش دست‌باف", id: 62444, tag: "a", number: 70 },
      { name: "آدرس‌یابی", id: 62443, tag: "a", number: 198 },
    ],
  },
];
